# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

api:
    resource:
        path: ../src/Controller/Api
        namespace: App\Controller\Api
    type: attribute
    prefix: /api
    name_prefix: api_

frontend:
    resource:
        path: ../src/Controller/Frontend
        namespace: App\Controller\Frontend
    type: attribute
    prefix: /
